// This file is auto-generated by @hey-api/openapi-ts
import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CallbackData,
  CallbackErrors,
  CallbackResponses,
  GetProfileData,
  GetProfileErrors,
  GetProfileResponses,
  GetRandomPlaylistData,
  GetRandomPlaylistErrors,
  GetRandomPlaylistResponses,
  LogInData,
  LogInErrors,
  LogInResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  SearchPlaylistsData,
  SearchPlaylistsErrors,
  SearchPlaylistsResponses,
  SyncPlaylistsData,
  SyncPlaylistsErrors,
  SyncPlaylistsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const callback = <ThrowOnError extends boolean = false>(
  options: Options<CallbackData, ThrowOnError>,
): RequestResult<CallbackResponses, CallbackErrors, ThrowOnError> =>
  (options.client ?? client).get<
    CallbackResponses,
    CallbackErrors,
    ThrowOnError
  >({ url: "/api/callback", ...options });

export const logIn = <ThrowOnError extends boolean = false>(
  options?: Options<LogInData, ThrowOnError>,
): RequestResult<LogInResponses, LogInErrors, ThrowOnError> =>
  (options?.client ?? client).post<LogInResponses, LogInErrors, ThrowOnError>({
    url: "/api/login",
    ...options,
  });

export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>(
    { url: "/api/logout", ...options },
  );

export const getProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetProfileData, ThrowOnError>,
): RequestResult<GetProfileResponses, GetProfileErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetProfileResponses,
    GetProfileErrors,
    ThrowOnError
  >({ url: "/api/profile", ...options });

export const getRandomPlaylist = <ThrowOnError extends boolean = false>(
  options: Options<GetRandomPlaylistData, ThrowOnError>,
): RequestResult<
  GetRandomPlaylistResponses,
  GetRandomPlaylistErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetRandomPlaylistResponses,
    GetRandomPlaylistErrors,
    ThrowOnError
  >({ url: "/api/random-playlist", ...options });

export const searchPlaylists = <ThrowOnError extends boolean = false>(
  options: Options<SearchPlaylistsData, ThrowOnError>,
): RequestResult<
  SearchPlaylistsResponses,
  SearchPlaylistsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    SearchPlaylistsResponses,
    SearchPlaylistsErrors,
    ThrowOnError
  >({ url: "/api/search-playlists", ...options });

export const syncPlaylists = <ThrowOnError extends boolean = false>(
  options?: Options<SyncPlaylistsData, ThrowOnError>,
): RequestResult<SyncPlaylistsResponses, SyncPlaylistsErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    SyncPlaylistsResponses,
    SyncPlaylistsErrors,
    ThrowOnError
  >({ url: "/api/sync-playlists", ...options });
