// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CallbackData, CallbackErrors, CallbackResponses, GetProfileData, GetProfileResponses, GetRandomPlaylistData, GetRandomPlaylistResponses, LogInData, LogInResponses, LogoutData, LogoutResponses, SearchPlaylistsData, SearchPlaylistsResponses, SyncPlaylistsData, SyncPlaylistsResponses, SyncProgressData, SyncProgressResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const callback = <ThrowOnError extends boolean = false>(options: Options<CallbackData, ThrowOnError>): RequestResult<CallbackResponses, CallbackErrors, ThrowOnError> => (options.client ?? client).get<CallbackResponses, CallbackErrors, ThrowOnError>({ url: '/api/callback', ...options });

export const logIn = <ThrowOnError extends boolean = false>(options?: Options<LogInData, ThrowOnError>): RequestResult<LogInResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogInResponses, unknown, ThrowOnError>({ url: '/api/login', ...options });

export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/api/logout', ...options });

export const getProfile = <ThrowOnError extends boolean = false>(options?: Options<GetProfileData, ThrowOnError>): RequestResult<GetProfileResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetProfileResponses, unknown, ThrowOnError>({ url: '/api/profile', ...options });

export const getRandomPlaylist = <ThrowOnError extends boolean = false>(options: Options<GetRandomPlaylistData, ThrowOnError>): RequestResult<GetRandomPlaylistResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetRandomPlaylistResponses, unknown, ThrowOnError>({ url: '/api/random-playlist', ...options });

export const searchPlaylists = <ThrowOnError extends boolean = false>(options: Options<SearchPlaylistsData, ThrowOnError>): RequestResult<SearchPlaylistsResponses, unknown, ThrowOnError> => (options.client ?? client).get<SearchPlaylistsResponses, unknown, ThrowOnError>({ url: '/api/search-playlists', ...options });

export const syncPlaylists = <ThrowOnError extends boolean = false>(options?: Options<SyncPlaylistsData, ThrowOnError>): RequestResult<SyncPlaylistsResponses, unknown, ThrowOnError> => (options?.client ?? client).post<SyncPlaylistsResponses, unknown, ThrowOnError>({ url: '/api/sync-playlists', ...options });

export const syncProgress = <ThrowOnError extends boolean = false>(options?: Options<SyncProgressData, ThrowOnError>): RequestResult<SyncProgressResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SyncProgressResponses, unknown, ThrowOnError>({ url: '/api/sync-progress', ...options });
