// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type DictionaryOfStringAndString = {
    [key: string]: string;
};

/**
 * the dto used to send an error response to the client
 */
export type ErrorResponse = {
    /**
     * the http status code sent to the client. default is 400.
     */
    statusCode?: number;
    /**
     * the message for the error response
     */
    message?: string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type Followers = {
    href?: string;
    total?: number;
};

export type GetProfileResponse = {
    user: PrivateUser;
    totalPlaylists: number;
    lastSyncedAt: null | string;
};

export type GetRandomPlaylistResponse = {
    randomPlaylist: PlaylistResponse;
};

export type ICollectionOfPlaylistResponse = Array<PlaylistResponse>;

export type ICollectionOfTrackResponse = Array<TrackResponse>;

export type Image = {
    height?: number;
    width?: number;
    url?: string;
};

export type ImageResponse = {
    url: string;
};

export type ListOfImage = Array<Image>;

export type LogInResponse = {
    loginUri: string;
};

export type PlaylistResponse = {
    id: string;
    name: string;
    description: string;
    ownerName: string;
    image: ImageResponse;
    tracks: ICollectionOfTrackResponse;
};

export type PrivateUser = {
    country?: string;
    displayName?: string;
    email?: string;
    externalUrls?: DictionaryOfStringAndString;
    followers?: Followers;
    href?: string;
    id?: string;
    images?: ListOfImage;
    product?: string;
    type?: string;
    uri?: string;
};

export type SearchPlaylistsResponse = {
    matchingPlaylists: ICollectionOfPlaylistResponse;
    totalPlaylists: number;
};

export type SyncPlaylistsResponse = {
    message: string;
};

export type SyncProgressResponse = {
    totalPlaylists: null | number;
    syncedPlaylists: number;
};

export type TrackResponse = {
    name: string;
    artistName: string;
    match: boolean;
};

export type Void = {
    [key: string]: unknown;
};

export type CallbackData = {
    body?: never;
    path?: never;
    query: {
        code: string;
    };
    url: '/api/callback';
};

export type CallbackErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
};

export type CallbackError = CallbackErrors[keyof CallbackErrors];

export type CallbackResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CallbackResponse = CallbackResponses[keyof CallbackResponses];

export type LogInData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LogInResponses = {
    /**
     * Success
     */
    200: LogInResponse;
};

export type LogInResponse2 = LogInResponses[keyof LogInResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout';
};

export type LogoutResponses = {
    /**
     * Success
     */
    200: Void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile';
};

export type GetProfileResponses = {
    /**
     * Success
     */
    200: GetProfileResponse;
};

export type GetProfileResponse2 = GetProfileResponses[keyof GetProfileResponses];

export type GetRandomPlaylistData = {
    body?: never;
    path?: never;
    query: {
        onlyOwnPlaylists: boolean;
    };
    url: '/api/random-playlist';
};

export type GetRandomPlaylistResponses = {
    /**
     * Success
     */
    200: GetRandomPlaylistResponse;
};

export type GetRandomPlaylistResponse2 = GetRandomPlaylistResponses[keyof GetRandomPlaylistResponses];

export type SearchPlaylistsData = {
    body?: never;
    path?: never;
    query: {
        searchTerm: string;
        showOnlyOwnPlaylists: boolean;
    };
    url: '/api/search-playlists';
};

export type SearchPlaylistsResponses = {
    /**
     * Success
     */
    200: SearchPlaylistsResponse;
};

export type SearchPlaylistsResponse2 = SearchPlaylistsResponses[keyof SearchPlaylistsResponses];

export type SyncPlaylistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sync-playlists';
};

export type SyncPlaylistsResponses = {
    /**
     * Success
     */
    200: SyncPlaylistsResponse;
};

export type SyncPlaylistsResponse2 = SyncPlaylistsResponses[keyof SyncPlaylistsResponses];

export type SyncProgressData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sync-progress';
};

export type SyncProgressResponses = {
    /**
     * Success
     */
    200: SyncProgressResponse;
};

export type SyncProgressResponse2 = SyncProgressResponses[keyof SyncProgressResponses];
