// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type GetProfileResponse = {
  user: GetProfileUserProfileResponse;
  totalPlaylists: number;
  lastSyncedAt: null | string;
};

export type GetProfileUserProfileResponse = {
  id: string;
  displayName: string;
  profileImageUrl: null | string;
};

export type GetRandomPlaylistResponse = {
  randomPlaylist: PlaylistResponse;
};

export type ICollectionOfPlaylistResponse = Array<PlaylistResponse>;

export type ICollectionOfTrackResponse = Array<TrackResponse>;

export type ImageResponse = {
  url: string;
};

export type LogInResponse = {
  loginUri: string;
};

export type PlaylistResponse = {
  id: string;
  name: string;
  description: string;
  ownerName: string;
  image: ImageResponse;
  tracks: ICollectionOfTrackResponse;
};

/**
 * RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:
 * ```app.UseFastEndpoints(c =&gt; c.Errors.UseProblemDetails())```
 */
export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: number;
  instance?: string;
  traceId?: string;
  /**
   * the details of the error
   */
  detail?: null | string;
  errors?: Array<{
    /**
     * the name of the error or property of the dto that caused the error
     */
    name?: string;
    /**
     * the reason for the error
     */
    reason?: string;
    /**
     * the code of the error
     */
    code?: null | string;
    /**
     * the severity of the error
     */
    severity?: null | string;
  }>;
};

export type SearchPlaylistsResponse = {
  matchingPlaylists: ICollectionOfPlaylistResponse;
  totalPlaylists: number;
};

export type SyncPlaylistsResponse = {
  message: string;
};

export type SyncProgressResponse = {
  totalPlaylists: null | number;
  syncedPlaylists: number;
};

export type TrackResponse = {
  name: string;
  artistName: string;
  match: boolean;
};

export type Void = {
  [key: string]: unknown;
};

export type CallbackData = {
  body?: never;
  path?: never;
  query: {
    code: string;
  };
  url: "/api/callback";
};

export type CallbackErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type CallbackError = CallbackErrors[keyof CallbackErrors];

export type CallbackResponses = {
  /**
   * No Content
   */
  204: void;
};

export type CallbackResponse = CallbackResponses[keyof CallbackResponses];

export type LogInData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/login";
};

export type LogInResponses = {
  /**
   * Success
   */
  200: LogInResponse;
};

export type LogInResponse2 = LogInResponses[keyof LogInResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/logout";
};

export type LogoutResponses = {
  /**
   * Success
   */
  200: Void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/profile";
};

export type GetProfileResponses = {
  /**
   * Success
   */
  200: GetProfileResponse;
};

export type GetProfileResponse2 =
  GetProfileResponses[keyof GetProfileResponses];

export type GetRandomPlaylistData = {
  body?: never;
  path?: never;
  query: {
    onlyOwnPlaylists: boolean;
  };
  url: "/api/random-playlist";
};

export type GetRandomPlaylistResponses = {
  /**
   * Success
   */
  200: GetRandomPlaylistResponse;
};

export type GetRandomPlaylistResponse2 =
  GetRandomPlaylistResponses[keyof GetRandomPlaylistResponses];

export type SearchPlaylistsData = {
  body?: never;
  path?: never;
  query: {
    searchTerm: string;
    showOnlyOwnPlaylists: boolean;
  };
  url: "/api/search-playlists";
};

export type SearchPlaylistsResponses = {
  /**
   * Success
   */
  200: SearchPlaylistsResponse;
};

export type SearchPlaylistsResponse2 =
  SearchPlaylistsResponses[keyof SearchPlaylistsResponses];

export type SyncPlaylistsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/sync-playlists";
};

export type SyncPlaylistsResponses = {
  /**
   * Success
   */
  200: SyncPlaylistsResponse;
};

export type SyncPlaylistsResponse2 =
  SyncPlaylistsResponses[keyof SyncPlaylistsResponses];

export type SyncProgressData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/sync-progress";
};

export type SyncProgressResponses = {
  /**
   * Success
   */
  200: SyncProgressResponse;
};

export type SyncProgressResponse2 =
  SyncProgressResponses[keyof SyncProgressResponses];
