name: spotify-playlist-search-tool

services:
  db:
    image: postgres
    container_name: spotify-playlist-search-tool-db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5433:5432"
