// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  callback,
  getProfile,
  getRandomPlaylist,
  logIn,
  logout,
  type Options,
  searchPlaylists,
  syncPlaylists,
  syncProgress,
} from "../sdk.gen";
import type {
  CallbackData,
  CallbackError,
  CallbackResponse,
  GetProfileData,
  GetProfileResponse2,
  GetRandomPlaylistData,
  GetRandomPlaylistResponse2,
  LogInData,
  LogInResponse2,
  LogoutData,
  LogoutResponse,
  SearchPlaylistsData,
  SearchPlaylistsResponse2,
  SyncPlaylistsData,
  SyncPlaylistsResponse2,
  SyncProgressData,
  SyncProgressResponse2,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const callbackQueryKey = (options: Options<CallbackData>) =>
  createQueryKey("callback", options);

export const callbackOptions = (options: Options<CallbackData>) =>
  queryOptions<
    CallbackResponse,
    CallbackError,
    CallbackResponse,
    ReturnType<typeof callbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await callback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: callbackQueryKey(options),
  });

export const logInMutation = (
  options?: Partial<Options<LogInData>>,
): UseMutationOptions<LogInResponse2, DefaultError, Options<LogInData>> => {
  const mutationOptions: UseMutationOptions<
    LogInResponse2,
    DefaultError,
    Options<LogInData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logIn({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const logoutMutation = (
  options?: Partial<Options<LogoutData>>,
): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<
    LogoutResponse,
    DefaultError,
    Options<LogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProfileQueryKey = (options?: Options<GetProfileData>) =>
  createQueryKey("getProfile", options);

export const getProfileOptions = (options?: Options<GetProfileData>) =>
  queryOptions<
    GetProfileResponse2,
    DefaultError,
    GetProfileResponse2,
    ReturnType<typeof getProfileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProfile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProfileQueryKey(options),
  });

export const getRandomPlaylistQueryKey = (
  options: Options<GetRandomPlaylistData>,
) => createQueryKey("getRandomPlaylist", options);

export const getRandomPlaylistOptions = (
  options: Options<GetRandomPlaylistData>,
) =>
  queryOptions<
    GetRandomPlaylistResponse2,
    DefaultError,
    GetRandomPlaylistResponse2,
    ReturnType<typeof getRandomPlaylistQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRandomPlaylist({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRandomPlaylistQueryKey(options),
  });

export const searchPlaylistsQueryKey = (
  options: Options<SearchPlaylistsData>,
) => createQueryKey("searchPlaylists", options);

export const searchPlaylistsOptions = (options: Options<SearchPlaylistsData>) =>
  queryOptions<
    SearchPlaylistsResponse2,
    DefaultError,
    SearchPlaylistsResponse2,
    ReturnType<typeof searchPlaylistsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchPlaylists({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchPlaylistsQueryKey(options),
  });

export const syncPlaylistsMutation = (
  options?: Partial<Options<SyncPlaylistsData>>,
): UseMutationOptions<
  SyncPlaylistsResponse2,
  DefaultError,
  Options<SyncPlaylistsData>
> => {
  const mutationOptions: UseMutationOptions<
    SyncPlaylistsResponse2,
    DefaultError,
    Options<SyncPlaylistsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await syncPlaylists({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const syncProgressQueryKey = (options?: Options<SyncProgressData>) =>
  createQueryKey("syncProgress", options);

export const syncProgressOptions = (options?: Options<SyncProgressData>) =>
  queryOptions<
    SyncProgressResponse2,
    DefaultError,
    SyncProgressResponse2,
    ReturnType<typeof syncProgressQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await syncProgress({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: syncProgressQueryKey(options),
  });
