name: spotify-playlist-search-tool-test

services:
  db:
    image: postgres
    container_name: spotify-playlist-search-tool-test-db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
