name: Test Migrations

on:
  workflow_dispatch: # Allows you to trigger this manually from the Actions tab
  push:

permissions:
  id-token: write
  contents: read

jobs:
  test-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::687979656894:role/playlist-search-tool-github-actions-role
          aws-region: eu-west-2

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        run: tofu init
        working-directory: ./infrastructure

    - name: OpenTofu Apply (to register outputs)
        run: tofu apply -auto-approve
        working-directory: ./infrastructure

      - name: Get OpenTofu Outputs
        id: tf-outputs
        run: |
          echo "public_subnet_1=$(tofu output -json public_subnet_ids | jq -r '.[0]')" >> $GITHUB_OUTPUT
          echo "public_subnet_2=$(tofu output -json public_subnet_ids | jq -r '.[1]')" >> $GITHUB_OUTPUT
          echo "ecs_sg=$(tofu output -raw ecs_tasks_security_group_id)" >> $GITHUB_OUTPUT
        working-directory: ./infrastructure

      - name: Run Database Migrations
        uses: geekcell/github-action-aws-ecs-run-task@v5.0.1
        with:
          cluster: playlist-search-tool-cluster
          task-definition: playlist-search-tool-migrations
          subnet-ids: |
            ${{ steps.tf-outputs.outputs.public_subnet_1 }}
            ${{ steps.tf-outputs.outputs.public_subnet_2 }}
          security-group-ids: ${{ steps.tf-outputs.outputs.ecs_sg }}
          assign-public-ip: 'ENABLED'
          tail-logs: true
          override-container: migrations
          override-container-command: dotnet SpotifyPlaylistSearchTool.Database.dll
          task-wait-until-stopped: true
          task-start-max-wait-time: 120
          task-stop-max-wait-time: 300
          task-check-state-delay: 6
